### ISSUE TITLE
using ip-set module get this error - Error creating WAFv2 IPSet: ValidationException: 1 validation error detected: Value '["10.0.0.0/16", │ "10.1.0.0/16"]' at 'addresses' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 50, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: .*\S.*] │       status code: 400, request id: 2889a028-8444-4209-86c2-8ef52deb2cd6 │ │   with aws_wafv2_ip_set.this[0], │   on main.tf line 1, in resource "aws_wafv2_ip_set" "this": │    1: resource "aws_wafv2_ip_set" "this" {

### ISSUE THREAD

**Issue by dharmeshn007** [woodonggyu/terraform-aws-wafv2#58]
### Contact

dharmesh37nadola@gmail.com

**Comment by woodonggyu** [comment]
@dharmeshn007 hello. Did you refer to the following?

When you create ip-set, you have to define addresses to your local file.
* https://github.com/woodonggyu/terraform-aws-wafv2/tree/main/examples/IP-sets

**Comment by dharmeshn007** [comment]
Hi Donggyu,

Yes i had refer the same code. I had also tried with the same file name and same ip addresses as well but give the same error every time.

Can you please spare some time to look at the issue i have described using below link.

[](https://serverfault.com/questions/1095574/how-to-pass-text-file-containing-list-of-thousands-ip-address-as-a-variable-whil)

**Comment by dharmeshn007** [comment]
Hi Donggyu,

Yes i had refer the same code. I had also tried with the same file name and same ip addresses as well but give the same error every time.

Can you please spare some time to look at the issue i have described using below link.

https://serverfault.com/questions/1095574/how-to-pass-text-file-containing-list-of-thousands-ip-address-as-a-variable-whil

**Comment by woodonggyu** [comment]
@dharmeshn007 I'm really sorry. that's my mistake. now, I found what is problem and updated.

**Comment by dharmeshn007** [comment]
@woodonggyu Issue is still persist as i can see it is not happening due to that's variable mistake. Even i have tried without module and tried to create a only ip-set resources it is through the same error.
As per my observation it is cause due to split function used at addresses. some how it can not convert data inside file into list(string). Also while using split with \n it is added \r to the ip address store in the file. For me it is strange error and tried all the possible way to change the behavior of output but bad luck every time.

**Comment by woodonggyu** [comment]
@dharmeshn007 

In my case, it works. I wonder your environment and version.
   * terraform version
   * os type

**Comment by dharmeshn007** [comment]
@woodonggyu 
Terraform version - Terraform v1.1.6
Os type - windows 10

**Comment by woodonggyu** [comment]
@dharmeshn007 Can I refer your project ? I will test it.

**Comment by dharmeshn007** [comment]
@woodonggyu Okay sure...But i have used the same terraform file and code as yours. Also i haven't updated any thing inside code.

**Comment by woodonggyu** [comment]
@dharmeshn007 I guess is that the problem is caused by OS differences.

Please refer to the link below.
* https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html

**Comment by dharmeshn007** [comment]
@woodonggyu So is there any other way to use with windows os?

**Comment by woodonggyu** [comment]
@dharmeshn007 I'm not sure. but I will try this

in main.tf

```terraform
addresses          = split("\r\n", file(var.addresses[count.index]))
```

**Comment by dharmeshn007** [comment]
I had already tried this.. not working

**Comment by dharmeshn007** [comment]
@woodonggyu Thanks man!!! Finally working...You save my day:)

**Comment by woodonggyu** [comment]
@dharmeshn007 Good man 👍  Could you share what is problem?

**Comment by dharmeshn007** [comment]
@woodonggyu I just follow your suggestion. split("\r\n", ) works for me
