### ISSUE TITLE
Experiemnts config on version.tf give errors because is deprecated. Can you updaste the repo?

### ISSUE THREAD

**Issue by Viox-LJ** [woodonggyu/terraform-aws-wafv2#70]
### Error Running the module

When try to run the module using the new terra version. Give me all time error regarding this line:

**experiments      = [module_variable_optional_attrs]**

Inside of version.tf file.
Can you update this?

**Comment by woodonggyu** [comment]
Hello, @Viox-LJ 
It has been updated You can check in version 2.4.0.
