### ISSUE TITLE
Experimental remove in SubModules

### ISSUE THREAD

**Issue by Viox-LJ** [woodonggyu/terraform-aws-wafv2#72]
### Contact

Plz remove also the experimental on the submodules, example: terraform-aws-wafv2/modules/ip-set/versions.tf

**Comment by Viox-LJ** [comment]
I think need do more checks becuase the module request some experimental features and not work. After fix the version part now have some problems inside of variables.tf:

│ Error: Optional object type attributes are experimental
│ 
│   on .terraform/modules/wafv2/variables.tf line 70:
│   70: variable "redacted_fields" {
│ 
│ This feature is currently an opt-in experiment, subject to change in future
│ releases based on feedback.
│ 
│ Activate the feature for this module by adding
│ module_variable_optional_attrs to the list of active experiments.
╵

╷
│ Error: Optional object type attributes are experimental
│ 
│   on .terraform/modules/wafv2/variables.tf line 82:
│   82: variable "logging_filter" {
│ 
│ This feature is currently an opt-in experiment, subject to change in future
│ releases based on feedback.
│ 
│ Activate the feature for this module by adding
│ module_variable_optional_attrs to the list of active experiments.

**Comment by woodonggyu** [comment]
@Viox-LJ 
I solved it by removing the optional function from the main module.
Could you please test again?
